/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/document/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question about a document
         * @description Parse a document and answer a question about its content using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Files up to 1000 pages and up to 500MB in size. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["document.ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured data from a document
         * @description Parse a document and extract structured data matching a provided JSON Schema using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Files up to 1000 pages and up to 500MB in size. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["document.extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a document
         * @description Extract text and page count from a document. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["document.parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question about an identity document
         * @description Parse an identity document and answer a question about its content using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["identity.ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured data from an identity document
         * @description Parse an identity document and extract structured data matching a provided JSON Schema using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["identity.extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an identity document
         * @description Extract text and structured data from an identity document. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["identity.parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoice/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question about an invoice
         * @description Parse an invoice and answer a question about its content using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["invoice.ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoice/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured data from an invoice
         * @description Parse an invoice and extract structured data matching a provided JSON Schema using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["invoice.extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoice/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse an invoice
         * @description Extract text and structured data from an invoice. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["invoice.parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankStatement/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a question about a bank statement
         * @description Parse a bank statement and answer a question about its content using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["bankStatement.ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankStatement/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract structured data from a bank statement
         * @description Parse a bank statement and extract structured data matching a provided JSON Schema using AI. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["bankStatement.extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bankStatement/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse a bank statement
         * @description Extract text and structured data from a bank statement. Supports PDF, Word (.docx), Excel (.xlsx), CSV, and Image (.png, .jpg) files. Provide the document via file upload, a public URL, or a base64-encoded string.
         */
        post: operations["bankStatement.parse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch academic papers by ID
         * @description Fetch specific academic publications by their unique identifiers with automatic provider detection and batch processing.
         */
        post: operations["academic.fetch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic/findCitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find citations for a paragraph
         * @description Find relevant academic citations for a paragraph by splitting it into sentences and scoring papers using semantic embedding similarity.
         */
        post: operations["academic.findCitations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/academic/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search academic papers
         * @description Search for academic publications across multiple databases with relevance ranking.
         */
        post: operations["academic.search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "document.ask": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /** @description The question to answer about the document */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier based on document page count and document complexity. 'nano': Uses lightweight models (likely better than GPT-5-nano). Supports PDF, Word, Excel, CSV. 'mini': Uses mid-range models (likely better than GPT-5-mini). Supports PDF, Word, Excel, CSV. 'pro': Uses capable models (likely better than GPT-5.2). Supports PDF, Word, Excel, CSV, Image. 'max': Uses the most powerful models (likely better than Claude Opus 4.6). Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /** @description The question to answer about the document */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier based on document page count and document complexity. 'nano': Uses lightweight models (likely better than GPT-5-nano). Supports PDF, Word, Excel, CSV. 'mini': Uses mid-range models (likely better than GPT-5-mini). Supports PDF, Word, Excel, CSV. 'pro': Uses capable models (likely better than GPT-5.2). Supports PDF, Word, Excel, CSV, Image. 'max': Uses the most powerful models (likely better than Claude Opus 4.6). Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The answer to the question */
                        markdown: string;
                        /**
                         * @description Model tier used to answer the question. 'nano': Supports PDF, Word, Excel, CSV. 'mini': Supports PDF, Word, Excel, CSV. 'pro': Supports PDF, Word, Excel, CSV, Image. 'max': Supports PDF, Word, Excel, CSV, Image.
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "document.extract": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the document */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the document. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier based on document page count and document complexity. 'nano': Uses lightweight models (likely better than GPT-5-nano). Supports PDF, Word, Excel, CSV. 'mini': Uses mid-range models (likely better than GPT-5-mini). Supports PDF, Word, Excel, CSV. 'pro': Uses capable models (likely better than GPT-5.2). Supports PDF, Word, Excel, CSV, Image. 'max': Uses the most powerful models (likely better than Claude Opus 4.6). Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the document */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the document. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier based on document page count and document complexity. 'nano': Uses lightweight models (likely better than GPT-5-nano). Supports PDF, Word, Excel, CSV. 'mini': Uses mid-range models (likely better than GPT-5-mini). Supports PDF, Word, Excel, CSV. 'pro': Uses capable models (likely better than GPT-5.2). Supports PDF, Word, Excel, CSV, Image. 'max': Uses the most powerful models (likely better than Claude Opus 4.6). Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted structured data matching the provided JSON Schema */
                        data?: unknown;
                        /**
                         * @description Model tier used to extract the data. 'nano': Supports PDF, Word, Excel, CSV. 'mini': Supports PDF, Word, Excel, CSV. 'pro': Supports PDF, Word, Excel, CSV, Image. 'max': Supports PDF, Word, Excel, CSV, Image.
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "document.parse": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. File up to 1000 pages, up to 500MB in size. Supports PDF, Word, Excel, CSV, Image. 'nano': For simple documents with plain text content. File up to 30 pages, up to 10MB in size. Supports PDF, Word, Excel, CSV. 'mini': For documents with tables and structured content. File up to 30 pages, up to 10MB in size. Supports PDF, Word, Excel, CSV. 'pro': For documents up to 30 pages with tables, handwritten text, figures, math, and Arabic. File up to 30 pages, up to 40MB in size. Supports PDF, Word, Excel, CSV, Image. 'max': For large documents with full Pro capabilities plus enhanced multilingual support. File up to 1000 pages, up to 500MB in size. Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the document file to fetch and parse
                     */
                    url?: string;
                    /** @description Document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded document file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. File up to 1000 pages, up to 500MB in size. Supports PDF, Word, Excel, CSV, Image. 'nano': For simple documents with plain text content. File up to 30 pages, up to 10MB in size. Supports PDF, Word, Excel, CSV. 'mini': For documents with tables and structured content. File up to 30 pages, up to 10MB in size. Supports PDF, Word, Excel, CSV. 'pro': For documents up to 30 pages with tables, handwritten text, figures, math, and Arabic. File up to 30 pages, up to 40MB in size. Supports PDF, Word, Excel, CSV, Image. 'max': For large documents with full Pro capabilities plus enhanced multilingual support. File up to 1000 pages, up to 500MB in size. Supports PDF, Word, Excel, CSV, Image.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted text content from the document */
                        markdown: string;
                        /** @description Total number of pages in the document */
                        pageCount: number;
                        /**
                         * @description Model tier used to parse the document. 'nano': Supports PDF, Word, Excel, CSV. 'mini': Supports PDF, Word, Excel, CSV. 'pro': Supports PDF, Word, Excel, CSV, Image. 'max': Supports PDF, Word, Excel, CSV, Image.
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Full HTML representation of the document content. Only available when using the 'max' model. Preserves rich formatting, tables, selection marks, and visual layout that cannot be fully represented in markdown. */
                        html?: string;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "identity.ask": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /** @description The question to answer about the identity document */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /** @description The question to answer about the identity document */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The answer to the question */
                        markdown: string;
                        /**
                         * @description Model tier used to answer the question
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "identity.extract": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the identity document */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the identity document. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the identity document */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the identity document. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted structured data matching the provided JSON Schema */
                        data?: unknown;
                        /**
                         * @description Model tier used to extract the data
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "identity.parse": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured identity document fields with standard accuracy. 'max': Extracts structured identity document fields with highest accuracy.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the identity document file to fetch and parse
                     */
                    url?: string;
                    /** @description Identity document file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded identity document file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured identity document fields with standard accuracy. 'max': Extracts structured identity document fields with highest accuracy.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted text content from the identity document */
                        markdown: string;
                        /** @description Total number of pages in the document */
                        pageCount: number;
                        /**
                         * @description Model tier used to parse the identity document
                         * @enum {string}
                         */
                        model: "pro" | "max";
                        /** @description Detected identity document type (e.g., passport, driver's license) */
                        documentType?: string;
                        /** @description Full HTML representation of the document content. Only available when using the 'max' model. Preserves rich formatting, tables, selection marks, and visual layout that cannot be fully represented in markdown. */
                        html?: string;
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "invoice.ask": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /** @description The question to answer about the invoice */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /** @description The question to answer about the invoice */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The answer to the question */
                        markdown: string;
                        /**
                         * @description Model tier used to answer the question
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "invoice.extract": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the invoice */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the invoice. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the invoice */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the invoice. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted structured data matching the provided JSON Schema */
                        data?: unknown;
                        /**
                         * @description Model tier used to extract the data
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "invoice.parse": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured invoice fields with standard accuracy. 'max': Extracts structured invoice fields with highest accuracy and fallback.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the invoice file to fetch and parse
                     */
                    url?: string;
                    /** @description Invoice file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded invoice file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured invoice fields with standard accuracy. 'max': Extracts structured invoice fields with highest accuracy and fallback.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted text content from the invoice */
                        markdown: string;
                        /** @description Total number of pages in the document */
                        pageCount: number;
                        /**
                         * @description Model tier used to parse the invoice
                         * @enum {string}
                         */
                        model: "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Full HTML representation of the document content. Only available when using the 'max' model. Preserves rich formatting, tables, selection marks, and visual layout that cannot be fully represented in markdown. */
                        html?: string;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "bankStatement.ask": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /** @description The question to answer about the bank statement */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /** @description The question to answer about the bank statement */
                    question: string;
                    /**
                     * @description Model tier for answering the question. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The answer to the question */
                        markdown: string;
                        /**
                         * @description Model tier used to answer the question
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "bankStatement.extract": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the bank statement */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the bank statement. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /** @description The prompt instructing the AI how to extract data from the bank statement */
                    prompt: string;
                    /** @description JSON Schema describing the structure of the data to extract from the bank statement. Can be a JSON object or a JSON string. */
                    schema: {
                        [key: string]: unknown;
                    } | string;
                    /**
                     * @description Model tier for extracting structured data. 'auto' (default): Automatically selects the best tier. 'nano': Uses lightweight models. 'mini': Uses mid-range models. 'pro': Uses capable models. 'max': Uses the most powerful models.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "auto" | "nano" | "mini" | "pro" | "max";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted structured data matching the provided JSON Schema */
                        data?: unknown;
                        /**
                         * @description Model tier used to extract the data
                         * @enum {string}
                         */
                        model: "nano" | "mini" | "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "bankStatement.parse": {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional document ID to associate with this request. Returned in the response and saved for usage tracking. */
                "x-pdfvector-document-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured bank statement fields with standard accuracy. 'max': Extracts structured bank statement fields with highest accuracy and fallback.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
                "multipart/form-data": {
                    /**
                     * Format: uri
                     * @description URL of the bank statement file to fetch and parse
                     */
                    url?: string;
                    /** @description Bank statement file upload via multipart form-data (PDF, DOCX, XLSX, CSV, PNG, JPG) */
                    file?: string;
                    /** @description Base64-encoded bank statement file content */
                    base64?: string;
                    /**
                     * @description Model tier for parsing. 'auto' (default): Automatically selects the best parsing strategy with intelligent fallback. 'pro': Extracts structured bank statement fields with standard accuracy. 'max': Extracts structured bank statement fields with highest accuracy and fallback.
                     * @default auto
                     * @enum {string}
                     */
                    model?: "pro" | "max" | "auto";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Extracted text content from the bank statement */
                        markdown: string;
                        /** @description Total number of pages in the document */
                        pageCount: number;
                        /**
                         * @description Model tier used to parse the bank statement
                         * @enum {string}
                         */
                        model: "pro" | "max";
                        /** @description Unique request identifier for this API call */
                        requestId: number;
                        /** @description Full HTML representation of the document content. Only available when using the 'max' model. Preserves rich formatting, tables, selection marks, and visual layout that cannot be fully represented in markdown. */
                        html?: string;
                        /** @description Document ID if provided via x-pdfvector-document-id header */
                        documentId?: string;
                    };
                };
            };
        };
    };
    "academic.fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Publication identifiers to fetch. Supports DOI, PubMed ID, ArXiv ID, Semantic Scholar ID, ERIC ID, Europe PMC ID, OpenAlex ID. */
                    ids: string[];
                    /** @description Specific publication fields to return. If omitted, returns all fields except providerData. */
                    fields?: ("doi" | "title" | "url" | "providerURL" | "authors" | "date" | "year" | "totalCitations" | "totalReferences" | "abstract" | "pdfURL" | "provider" | "providerData")[] | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: {
                            /** @description Original input identifier */
                            id: string;
                            /** @description Provider that returned this result */
                            detectedProvider?: string | null;
                            doi?: string | null;
                            title?: string | null;
                            url?: string | null;
                            providerURL?: string | null;
                            authors?: {
                                name: string;
                                url?: string | null;
                            }[] | null;
                            date?: string | null;
                            year?: number | null;
                            totalCitations?: number | null;
                            totalReferences?: number | null;
                            abstract?: string | null;
                            pdfURL?: string | null;
                            provider?: string | null;
                            providerData?: {
                                [key: string]: unknown;
                            } | null;
                        }[];
                        errors?: {
                            id: string;
                            error: string;
                            code?: string | null;
                        }[] | null;
                        requestId: number;
                    };
                };
            };
        };
    };
    "academic.findCitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Text paragraph to find relevant academic citations for */
                    paragraph: string;
                    /**
                     * @description Academic databases to search for citations
                     * @default [
                     *       "semantic-scholar"
                     *     ]
                     */
                    providers?: ("semantic-scholar" | "pubmed" | "arxiv" | "google-scholar" | "eric" | "europe-pmc" | "openalex")[];
                    /** @description Specific citation fields to return. If omitted, returns all fields except providerData. */
                    fields?: ("doi" | "title" | "url" | "providerURL" | "authors" | "date" | "year" | "totalCitations" | "totalReferences" | "abstract" | "pdfURL" | "provider" | "providerData")[] | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: {
                            sentence: string;
                            citations: {
                                /** @description Relevance score (0-10) */
                                score: number;
                                doi?: string | null;
                                title?: string | null;
                                url?: string | null;
                                providerURL?: string | null;
                                authors?: {
                                    name: string;
                                    url?: string | null;
                                }[] | null;
                                date?: string | null;
                                year?: number | null;
                                totalCitations?: number | null;
                                totalReferences?: number | null;
                                abstract?: string | null;
                                pdfURL?: string | null;
                                provider?: string | null;
                                providerData?: {
                                    [key: string]: unknown;
                                } | null;
                            }[];
                        }[];
                        sentenceCount: number;
                        totalCitations: number;
                        errors?: string[] | null;
                        requestId: number;
                    };
                };
            };
        };
    };
    "academic.search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Search query string for academic papers */
                    query: string;
                    /**
                     * @description Academic databases to search
                     * @default [
                     *       "semantic-scholar"
                     *     ]
                     */
                    providers?: ("semantic-scholar" | "pubmed" | "arxiv" | "google-scholar" | "eric" | "europe-pmc" | "openalex")[];
                    /**
                     * @description Results offset
                     * @default 0
                     */
                    offset?: number;
                    /**
                     * @description Results per provider
                     * @default 20
                     */
                    limit?: number;
                    /** @description Filter papers published from this year */
                    yearFrom?: number | null;
                    /** @description Filter papers published up to this year */
                    yearTo?: number | null;
                    /** @description Specific publication fields to return. If omitted, returns all fields except providerData. */
                    fields?: ("doi" | "title" | "url" | "providerURL" | "authors" | "date" | "year" | "totalCitations" | "totalReferences" | "abstract" | "pdfURL" | "provider" | "providerData")[] | null;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        estimatedTotalResults: number;
                        results: {
                            doi?: string | null;
                            title?: string | null;
                            url?: string | null;
                            providerURL?: string | null;
                            authors?: {
                                name: string;
                                url?: string | null;
                            }[] | null;
                            date?: string | null;
                            year?: number | null;
                            totalCitations?: number | null;
                            totalReferences?: number | null;
                            abstract?: string | null;
                            pdfURL?: string | null;
                            provider?: ("semantic-scholar" | "pubmed" | "arxiv" | "google-scholar" | "eric" | "europe-pmc" | "openalex") | null;
                            providerData?: {
                                [key: string]: unknown;
                            } | null;
                        }[];
                        errors?: {
                            provider: string;
                            message: string;
                            code?: string | null;
                            details?: {
                                [key: string]: unknown;
                            } | null;
                        }[] | null;
                        requestId: number;
                    };
                };
            };
        };
    };
}
